name: image_editor_common
description: Edit your image data and output to file/memory on Android and iOS.
version: 1.0.1
publish_to: none
repository: https://github.com/fluttercandies/flutter_image_editor

environment:
  sdk: ">=3.5.2 <4.0.0"
  flutter: ">=3.24.0"
  
dependencies:
  flutter:
    sdk: flutter
  image_editor_platform_interface:
    git: https://github.com/kumsumit/image_editor_platform_interface.git

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  plugin:
    implements: image_editor
    platforms:
      android:
        package: com.fluttercandies.image_editor
        pluginClass: ImageEditorPlugin
        dartPluginClass: ImageEditorCommon
      ios:
        pluginClass: ImageEditorPlugin
        dartPluginClass: ImageEditorCommon
      macos:
        pluginClass: ImageEditorPlugin
        dartPluginClass: ImageEditorCommon
